Algoritmo "idades"

Var

   idade1, idade2 : inteiro
   nome1, nome2 : caractere
   M : real
Inicio

      escreval("Digite o seu nome: ")
      leia(nome1)
      escreval("Digite a sua idade: ")
      leia(idade1)
      
      escreval("Digite o seu nome: ")
      leia(nome2)
      escreval("Digite a sua idade: ")
      leia(idade2)
      
      M <- (idade1 + idade2) /2
      
      escreval("A idade média entre ", nome1," e ", nome2, " é de: ", M)
      




Fimalgoritmo