Algoritmo "matriz3x2"

Var

   m: vetor[1..3, 1..2] de inteiro
   l, c: inteiro

Inicio

      para  l <- 1 ate 3 faca
            para c <- 1 ate 2 faca
            escreva("DIGITE O VALOR DA POSIÇÃO [", l, ",", c, "]: " )
            leia(m[l,c])
            fimpara
      fimpara

      para l <- 1 ate 3 faca
           para c <- 1 ate 2 faca
           escreva(m[l,c]: 6)
           fimpara
           escreval()
      fimpara


Fimalgoritmo