Algoritmo "tabuada"

Var

N, i, resultado : inteiro

Inicio

      escreval("-----------TABUADA-------------")
      escreval
      escreva("DIGITE O VALOR QUE VOCÊ QUER VER A TABUADA: ")
      leia(N)
      escreval
      
      escreval("------------------------------")
      
      para i de 1 ate 10 faca
           resultado<- i*N
           escreval(i, " X ", N, " = ", resultado)
      fimpara

Fimalgoritmo